storage: ../tmp/local-registry/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m

packages:
  "**":
    access: $all
    publish: $all
    unpublish: $all

    proxy: npmjs

log:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true
