packages:
  - apps/*
  - libs/*
  - libs/**

linkWorkspacePackages: true
onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@compodoc/compodoc"
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@scarf/scarf"
  - "@sentry/cli"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - bigint-buffer
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - keccak
  - nx
  - protobufjs
  - sharp
  - spawn-sync
  - unrs-resolver
  - utf-8-validate
