packages:
  - apps/*
  - libs/*
  - libs/**

catalog:
  '@mkvlrn/result': ^1.1.4
  '@tanstack/query-sync-storage-persister': ^5.80.10
  '@theguild/remark-mermaid': ^0.3.0
  '@wagmi/connectors': ^5.8.5
  '@wagmi/core': ^2.17.3
  chalk: ^5.4.1
  cli-table3: ^0.6.5
  cmdk: ^1.1.1
  commander: ^12.1.0
  date-fns: ^4.1.0
  decimal.js: ^10.5.0
  envalid: ^8.0.0
  file-loader: ^6.2.0
  inquirer: ^12.6.3
  isbot: ^5.1.27
  jsdom: ~26.1.0
  pino-pretty: ^13.0.0
  reflect-metadata: ^0.2.2
  tunnelmole: ^2.4.0
  use-query-params: ^2.2.1
  usehooks-ts: ^3.1.1
  viem: ^2.31.3
  zod: ^3.25.67

catalogs:
  api:
    '@apollo/server': ^4.12.2
    '@compodoc/compodoc': ^1.1.26
    '@nestia/editor': ^7.0.0
    '@nestjs/apollo': ^13.1.0
    '@nestjs/common': ^11.1.3
    '@nestjs/config': ^4.0.2
    '@nestjs/core': ^11.1.3
    '@nestjs/graphql': ^13.1.0
    '@nestjs/platform-express': ^11.1.3
    '@nestjs/serve-static': ^5.0.3
    '@nestjs/swagger': ^11.2.0
    '@nestjs/testing': ^11.1.3
    '@payloadcms/db-postgres': ^3.43.0
    '@payloadcms/db-sqlite': ^3.43.0
    '@payloadcms/email-resend': ^3.43.0
    '@payloadcms/next': ^3.43.0
    '@payloadcms/plugin-form-builder': ^3.43.0
    '@payloadcms/richtext-lexical': ^3.43.0
    '@payloadcms/storage-s3': ^3.43.0
    '@payloadcms/ui': ^3.43.0
    '@scalar/nestjs-api-reference': ^0.5.4
    '@scalar/nextjs-api-reference': ^0.8.6
    axios: ^1.10.0
    drizzle-kit: 0.31.4
    get-port: ^7.1.0
    graphql: ^16.10.0
    graphql-request: ^7.2.0
    graphql-voyager: ^2.1.0
    gray-matter: ^4.0.3
    payload: ^3.43.0
    payload-oapi: ^0.2.3
    payload-oauth2: ^1.0.15
    qs-esm: ^7.0.2
  build:
    '@commitlint/types': ^19.8.0
    '@monodon/rust': ^2.3.0
    '@nx/devkit': 21.3.7
    '@nx/js': 21.3.7
    '@nx/next': 21.3.7
    '@nx/node': 21.3.7
    '@nx/playwright': 21.3.7
    '@nx/react': 21.3.7
    '@nx/storybook': 21.3.7
    '@nx/vite': 21.3.7
    '@nx/web': 21.3.7
    '@nx/webpack': 21.3.7
    '@nx/workspace': 21.3.7
    '@storybook/types': ^8.6.14
    '@swc-node/register': ^1.10.10
    '@swc/cli': ~0.7.7
    '@swc/core': ^1.12.6
    '@swc/helpers': 0.5.17
    '@types/express': ^5.0.3
    '@types/mdx': ^2.0.13
    '@types/node': 22.14.0
    '@types/react': 19.1.9
    '@types/react-dom': 19.1.7
    '@types/supertest': ^6.0.3
    '@vitejs/plugin-react': ^4.5.2
    nx: 21.3.7
    swc-loader: ^0.2.6
    tsconfig-paths-webpack-plugin: ^4.2.0
    tslib: ^2.8.1
    typescript: ^5.8.3
    verdaccio: ^6.1.4
    vite: 6.3.5
    vite-node: ^3.2.3
    vite-plugin-dts: ~4.5.0
    vite-tsconfig-paths: ^5.1.4
  ci:
    '@netlify/edge-functions': ^2.11.1
    '@netlify/plugin-nextjs': ^5.11.6
    '@netlify/vite-plugin-react-router': ^1.0.1
    '@pulumi/pulumi': ^3.177.0
    '@pulumiverse/vercel': ^3.2.1
    '@sentry/nextjs': ^9.30.0
    '@vercel/blob': ^0.27.3
    '@vercel/node': ^5.3.7
    chromatic: ^13.0.1
  fuels:
    '@fuels/connectors': 0.44.1
    '@fuels/react': 0.40.0
    fuels: 0.101.3
  script:
    '@eslint/config-inspector': ^1.1.0
    '@statelyai/inspect': ^0.4.0
    '@xstate/cli': ^0.5.17
    drizzle-lab: ^0.11.0
    node-modules-inspector: ^1.0.0
    tsc-alias: ^1.8.16
    tsup: ^8.5.0
    tsx: ^4.20.3
    vue-tsc: ^2.2.10
  style:
    '@antfu/eslint-config': ^5.0.0
    '@commitlint/cli': ^19.8.0
    '@commitlint/config-conventional': ^19.8.0
    '@commitlint/cz-commitlint': ^19.8.0
    '@eslint-react/eslint-plugin': ^1.52.2
    '@eslint/compat': ^1.3.0
    '@eslint/eslintrc': ^3.3.1
    '@eslint/js': ^9.29.0
    '@next/eslint-plugin-next': ^15.3.4
    '@nx/eslint': 21.3.7
    '@nx/eslint-plugin': 21.3.7
    '@typescript-eslint/eslint-plugin': ^8.34.1
    '@typescript-eslint/parser': ^8.34.1
    commitizen: ^4.3.1
    commitlint: ^19.8.0
    eslint: ^9.29.0
    eslint-config-next: 15.4.5
    eslint-config-prettier: 10.1.8
    eslint-plugin-format: ^1.0.1
    eslint-plugin-import: 2.32.0
    eslint-plugin-jsx-a11y: 6.10.2
    eslint-plugin-playwright: ^2.2.0
    eslint-plugin-prettier: ^5.5.0
    eslint-plugin-react: 7.37.5
    eslint-plugin-react-hooks: 5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-storybook: 9.0.18
    lint-staged: ^16.1.2
    prettier: ^3.5.3
    typescript-eslint: ^8.34.1
  test:
    '@fuels/playwright-utils': ^0.58.0
    '@playwright/test': ^1.53.1
    '@serenity-js/assertions': ^3.31.17
    '@serenity-js/console-reporter': ^3.31.17
    '@serenity-js/core': ^3.31.17
    '@serenity-js/playwright': ^3.31.17
    '@serenity-js/playwright-test': ^3.31.17
    '@serenity-js/rest': ^3.31.17
    '@serenity-js/serenity-bdd': ^3.31.17
    '@serenity-js/web': ^3.31.17
    '@testing-library/dom': 10.4.1
    '@testing-library/react': 16.3.0
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    playwright-lighthouse: ^4.0.0
    supertest: ^7.1.1
    vitest: ^3.2.4
  ui:
    '@fumadocs/mdx-remote': ^1.3.3
    '@radix-ui/react-accordion': ^1.2.11
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-checkbox': ^1.3.2
    '@radix-ui/react-dialog': ^1.1.14
    '@radix-ui/react-dropdown-menu': ^2.1.15
    '@radix-ui/react-icons': ^1.3.2
    '@radix-ui/react-label': ^2.1.7
    '@radix-ui/react-navigation-menu': ^1.2.13
    '@radix-ui/react-popover': ^1.1.14
    '@radix-ui/react-radio-group': ^1.3.7
    '@radix-ui/react-scroll-area': ^1.2.9
    '@radix-ui/react-select': ^2.2.5
    '@radix-ui/react-separator': ^1.1.7
    '@radix-ui/react-slot': ^1.2.3
    '@radix-ui/react-tabs': ^1.1.12
    '@radix-ui/react-tooltip': ^1.2.7
    '@radix-ui/react-visually-hidden': ^1.2.3
    '@react-router/dev': ^7.6.2
    '@react-router/node': ^7.6.2
    '@react-router/serve': ^7.6.2
    '@storybook/addon-a11y': 9.0.18
    '@storybook/addon-designs': ^10.0.1
    '@storybook/addon-docs': 9.0.18
    '@storybook/addon-links': 9.0.18
    '@storybook/addon-themes': 9.0.18
    '@storybook/nextjs': 9.0.18
    '@storybook/nextjs-vite': ^9.0.12
    '@storybook/preview-api': ^8.6.14
    '@tabler/icons-react': ^3.34.0
    '@tailwindcss/postcss': ^4.1.10
    '@tailwindcss/typography': ^0.5.16
    '@tailwindcss/vite': ^4.1.10
    '@tanstack/react-query': ^5.80.10
    '@tanstack/react-query-devtools': ^5.80.10
    '@tanstack/react-query-persist-client': ^5.80.10
    '@tanstack/react-table': ^8.21.3
    '@whitespace/storybook-addon-html': ^7.0.0
    '@wxt-dev/auto-icons': ^1.0.2
    '@wxt-dev/module-react': ^1.1.3
    '@wxt-dev/webextension-polyfill': ^1.0.0
    '@xstate/react': ^6.0.0
    autoprefixer: ^10.4.21
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    framer-motion: ^12.18.1
    fumadocs-core: 15.6.7
    fumadocs-docgen: ^2.0.1
    fumadocs-mdx: 11.7.3
    fumadocs-openapi: ^9.0.12
    fumadocs-ui: 15.6.7
    katex: ^0.16.22
    lexical: 0.33.1
    likec4: ^1.32.2
    lucide-react: ^0.536.0
    mermaid: ^11.6.0
    motion: ^12.18.1
    next: ^15.3.4
    next-query-params: ^5.1.0
    next-themes: ^0.4.6
    postcss: ^8.5.6
    react: 19.1.1
    react-device-detect: ^2.2.3
    react-dom: 19.1.1
    react-icons: ^5.5.0
    react-loading-skeleton: ^3.5.0
    react-router: ^7.6.2
    react-router-devtools: ^5.0.6
    react-select: ^5.10.1
    react-tooltip: ^5.29.1
    rehype-katex: ^7.0.1
    rehype-mermaid: ^2.1.0
    remark-math: ^6.0.0
    rxjs: ^7.8.2
    sharp: ^0.34.3
    shiki: ^3.6.0
    sonner: ^2.0.6
    storybook: 9.0.18
    storybook-dark-mode: ^4.0.2
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.10
    tailwindcss-animate: ^1.0.7
    tw-animate-css: ^1.3.4
    webextension-polyfill: ^0.12.0
    wxt: ^0.20.7
    xstate: ^5.20.0
    zustand: ^5.0.5

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@compodoc/compodoc'
  - '@fuel-ts/forc'
  - '@fuel-ts/fuel-core'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bigint-buffer
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - keccak
  - nx
  - protobufjs
  - sharp
  - spawn-sync
  - tunnelmole
  - unrs-resolver
  - utf-8-validate
