export const DOMAINS = [
  "https://mainnet-explorer.fuel.network",
  "https://explorer-indexer-mainnet.fuel.network",
  "https://verified-assets.fuel.network",
  "https://mira-dex.squids.live/mira-indexer@v3/api/graphql",
  "https://firebasestorage.googleapis.com",
  "https://github.com",
  "https://img.icons8.com",
  "https://upload.wikimedia.org",
  "https://12factor.net",
  "https://firebasestorage.googleapis.com",
  "https://verified-assets.fuel.network",
  "https://4021016264-files.gitbook.io",
  "https://i.imgur.com",
];
