# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
# yazi-rs.github.io/docs/configuration/overview

[manager]
ratio          = [ 2, 2, 4 ]
show_hidden    = true
show_symlink   = true

[preview]
wrap            = "yes"
tab_size        = 2
