/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.2
*/

import {ContractFactory as __ContractFactory, decompressBytecode} from "fuels";
import type {Provider, Account, DeployContractOptions} from "fuels";

import {TestTargetContract} from "./TestTargetContract";

const bytecode = decompressBytecode(
  "H4sIAAAAAAAAA4VTPWgUQRj9LneQ7RxMhHNDdBUSLyC6oAmWc+wdm3P3uBFtl51G0CaGVQ5BhBULsYuCeulSpnN21yKdV6ZMmfIKiwRzmEIhqeKb3Q2mkVwzb9/3vTffz5x5aNMLohrlv+puee4FJ8MKOzmhD0RGtEeM/fw6FD/IECNO60f2d2jIPBCIV0XgHFZYk4ZBS94XntoOx+yycNN7sm0Z4DrCSwxw18BJzekz8JQfdCwKesqPBBmsu0jh2PZFT41klyHfmpVjmwk3Y9JVLHCVz9rTMXx8zYleOkAe4ukAeKvEW6KX2QXObHixAidCtuHVUzul94xwlZVzXsplJ9dy1D6UHfToJKvIuRUt0yTO26hf80w46aFsItdJN2XTyr/hvSfbxMx9pufy3nR2CF6b0BxpX3Pf0vzbqeYFPtXEzFpEfU4XC21aP6N990+bNs5o35gueA/5vdSQXQu8rfmVhXbtdb9FExGnV0ucKHjEKeI1mgdGD43wYHUuatUwVzYfHtAN9GzjvjpiMfqo4664+E5jxJYLrHSP9cBRV4KH6irmbmEOButMx5e6c9T3qYLdT0Y+Tcx0W8N8dw8WaV4QNWZr3OSrxNo1HrYFekkG4ZjuhGN+F3NchLcs7k12ynuf5N84Uctuye2ilpdlnSyvxVXXRRPz9xKFXpYE3hDi2JNay/fgpthvvh8BvF3ibbwBXuCMw3OjwImugaG/m1onvIyK/WeYcWaV2MJbUAVO4GHp97cw12T0Cb1/Nk7fPhmmE5PpjijwNjBni/SsGs632PxN9FHHjxkNkP8FuvXqSOurZ/TMdEYkf21o/4r5h2kNM4/pVFM9R0P/0/QfR8+fPlsp/s5UXSsB/QX/2rgi8AMAAA=="
);

export class TestTargetContractFactory extends __ContractFactory<TestTargetContract> {
  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(
      bytecode,
      TestTargetContract.abi,
      accountOrProvider,
      TestTargetContract.storageSlots
    );
  }

  static deploy(wallet: Account, options: DeployContractOptions = {}) {
    const factory = new TestTargetContractFactory(wallet);
    return factory.deploy(options);
  }
}
