name: Initialize
description: Common steps for app initialization

inputs:
  aws_access_key:
    description: 'CICD user AWS Access Key Id'
    required: true
  aws_secret_access_key:
    description: 'CICD user AWS Secret Access Key'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: us-east-1

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Build next app
      shell: bash
      run: npm install --force && npm run build
