import {LiquidityData, LiquidityShape} from "./simulated-distribution";

export const spot = [
  {
    price: "675",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "978",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "1280",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 54,
    assetBHeight: 66,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "1583",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "1885",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "2175",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
];

export const curve = [
  {
    price: "675",
    assetAHeight: 60,
    assetBHeight: 0,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 61,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 62,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 63,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 64,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 65,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 66,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 67,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 68,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 69,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 70,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 71,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 72,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 73,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 74,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 75,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 76,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 77,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 78,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 79,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 80,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 81,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 82,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 83,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "978",
    assetAHeight: 84,
    assetBHeight: 0,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 85,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 86,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 87,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 88,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 89,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 90,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 91,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 92,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 93,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 94,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 95,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 96,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 97,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 98,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 99,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 100,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 101,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 102,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 103,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 104,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 105,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 106,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 107,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "1280",
    assetAHeight: 108,
    assetBHeight: 0,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 109,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 110,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 111,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 112,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 113,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 114,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 115,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 116,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 117,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 118,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 119,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 54,
    assetBHeight: 66,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 119,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 118,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 117,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 116,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 115,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 114,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 113,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 112,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 111,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 110,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 109,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "1583",
    assetAHeight: 0,
    assetBHeight: 108,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 107,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 106,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 105,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 104,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 103,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 102,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 101,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 100,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 99,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 98,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 97,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 96,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 95,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 94,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 93,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 92,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 91,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 90,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 89,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 88,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 87,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 86,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 85,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "1885",
    assetAHeight: 0,
    assetBHeight: 84,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 83,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 82,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 81,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 80,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 79,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 78,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 77,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 76,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 75,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 74,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 73,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 72,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 71,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 70,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 69,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 68,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 67,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 66,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 65,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 64,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 63,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 62,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "2175",
    assetAHeight: 0,
    assetBHeight: 61,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
];

export const bidask = [
  {
    price: "675",
    assetAHeight: 140,
    assetBHeight: 0,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 139,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 137,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 136,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 135,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 133,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 132,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 131,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 129,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 128,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 127,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 125,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 124,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 123,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 121,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 120,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 119,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 117,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 116,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 115,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 113,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 112,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 111,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 109,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "978",
    assetAHeight: 108,
    assetBHeight: 0,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 107,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 105,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 104,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 103,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 101,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 100,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 99,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 97,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 96,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 95,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 93,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 92,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 91,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 89,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 88,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 87,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 85,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 84,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 83,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 81,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 80,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 79,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 77,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "1280",
    assetAHeight: 76,
    assetBHeight: 0,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 75,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 73,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 72,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 71,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 69,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 68,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 67,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 65,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 64,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 63,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 61,
    assetBHeight: 0,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 27,
    assetBHeight: 33,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 61,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 63,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 64,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 65,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 67,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 68,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 69,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 71,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 72,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 73,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 75,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "1583",
    assetAHeight: 0,
    assetBHeight: 76,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 77,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 79,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 80,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 81,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 83,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 84,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 85,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 87,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 88,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 89,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 91,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 92,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 93,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 95,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 96,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 97,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 99,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 100,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 101,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 103,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 104,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 105,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 107,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "1885",
    assetAHeight: 0,
    assetBHeight: 108,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 109,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 111,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 112,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 113,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 115,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 116,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 117,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 119,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 120,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 121,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 123,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 124,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 125,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 127,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 128,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 129,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 131,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 132,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 133,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 135,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 136,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "",
    assetAHeight: 0,
    assetBHeight: 137,
    showPrice: false,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
  {
    price: "2175",
    assetAHeight: 0,
    assetBHeight: 139,
    showPrice: true,
    binId: 1,
    asset0Value: 1,
    asset1Value: 1,
  },
];

export const graphVisualization: Record<LiquidityShape, LiquidityData> = {
  spot,
  curve,
  bidask,
};
