name: Deploy to prod

on: workflow_dispatch

jobs:
  prod_deploy:
    runs-on: ubuntu-latest
    # see https://docs.github.com/en/actions/learn-github-actions/expressions#example-matching-an-array-of-strings
    if: github.ref == 'refs/heads/main' && contains(fromJSON('["mpoplavkov", "dmihal", "FossilFrank"]'), github.event.sender.login)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/initialize
        with:
          aws_access_key: ${{ secrets.MIRA_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.MIRA_AWS_SECRET_ACCESS_KEY }}

      - name: Deploy static site to S3 bucket
        env:
          BUCKET_NAME: "mira.ly"
        run: aws s3 sync ./out/ s3://${{ env.BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.PROD_CLOUD_FRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
